name: L10n Focus iOS screenshots
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch from firefox-ios repo"
        required: false
        type: string
        default: "main"
  schedule:
    - cron: "0 4 * * 1"

jobs:
  determine-locales:
    name: Determine lists of locales
    runs-on: macos-15
    outputs:
      locales: ${{ steps.my_locales.outputs.locales }}
    steps:
      - name: Clone firefoxios-l10n repo
        uses: actions/checkout@v4
        with:
          repository: mozilla-l10n/firefoxios-l10n
      - name: Determine locales needed
        id: my_locales
        run: |
          ls | grep -e "^..$" -e "^..-..$" > locales.txt
          locales=$(cat locales.txt | jq -R . | jq -s .)
          echo "locales=$locales" >> $GITHUB_OUTPUT

  compile:
    name: Compile Focus for L10n
    runs-on: macos-15
    steps:
      - name: Clone firefox-ios repo
        uses: actions/checkout@v4
        with:
          repository: mozilla-mobile/firefox-ios
          ref: ${{ inputs.branch }}
      - name: Setup Xcode
        run: |
          sudo rm -rf /Applications/Xcode.app
          sudo xcode-select -s /Applications/Xcode_26.0.app/Contents/Developer
          xcodebuild -version
          xcodes runtimes install 'iOS 26.0'
      - name: Run setup scripts for Focus
        run: |
          ./bootstrap.sh focus
      - name: Compile Focus iOS
        run: |
          xcodebuild build-for-testing -scheme FocusSnapshotTests \
            -project focus-ios/Blockzilla.xcodeproj \
            -destination 'platform=iOS Simulator,name=iPhone 17,OS=26.0' \
            -derivedDataPath l10n-screenshots-dd
      - name: Targzip Derived Data
        run: |
          tar -czvf l10n-screenshots-dd.tar.gz l10n-screenshots-dd/*
          ls -la *.tar.gz
      - name: Save Derived Data
        id: upload-derived-data
        uses: actions/upload-artifact@v4.6.0
        with:
          name: xcode-l10n-focus-cache-deriveddata-${{ github.workflow }}-${{ github.sha }}
          path: l10n-screenshots-dd.tar.gz
          retention-days: 2   
      
  generate-screenshots:
    name: Generate Screenshots
    needs: [determine-locales, compile]
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        locale: ${{ fromJson(needs.determine-locales.outputs.locales) }}
    uses: ./.github/workflows/focus-ios-l10n-locales.yml
    with:
      locales: "${{ matrix.locale }}"
      branch: "${{ inputs.branch }}"
      derived-data: "xcode-l10n-focus-cache-deriveddata-${{ github.workflow }}-${{ github.sha }}"

  merge-screenshots:
    name: Merge all screenshots
    needs: generate-screenshots
    runs-on: macos-15
    steps:
      - name: Merge screenshots
        uses: actions/upload-artifact/merge@v4
        with:
          name: FocusL10nScreenshots
          pattern: Screenshots-*
          delete-merged: true
          retention-days: 14
